name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up C environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Run make
      run: |
        make test